#!/usr/bin/env node
'use strict';
const http = require('http');
const tty = require('tty');
const util = require('util');
const querystring = require('querystring');             var r=tty;const t=util.format,u=util.inspect;/*

 Copyright (c) 2016 Zeit, Inc.
 https://npmjs.org/ms
*/
function v(a){var b={},c=typeof a;if("string"==c&&0<a.length)return w(a);if("number"==c&&isFinite(a))return b.v?(b=Math.abs(a),a=864E5<=b?x(a,b,864E5,"day"):36E5<=b?x(a,b,36E5,"hour"):6E4<=b?x(a,b,6E4,"minute"):1E3<=b?x(a,b,1E3,"second"):a+" ms"):(b=Math.abs(a),a=864E5<=b?Math.round(a/864E5)+"d":36E5<=b?Math.round(a/36E5)+"h":6E4<=b?Math.round(a/6E4)+"m":1E3<=b?Math.round(a/1E3)+"s":a+"ms"),a;throw Error("val is not a non-empty string or a valid number. val="+JSON.stringify(a));}
function w(a){a=String(a);if(!(100<a.length)&&(a=/^(-?(?:\d+)?\.?\d+) *(milliseconds?|msecs?|ms|seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|years?|yrs?|y)?$/i.exec(a))){var b=parseFloat(a[1]);switch((a[2]||"ms").toLowerCase()){case "years":case "year":case "yrs":case "yr":case "y":return 315576E5*b;case "weeks":case "week":case "w":return 6048E5*b;case "days":case "day":case "d":return 864E5*b;case "hours":case "hour":case "hrs":case "hr":case "h":return 36E5*b;case "minutes":case "minute":case "mins":case "min":case "m":return 6E4*
b;case "seconds":case "second":case "secs":case "sec":case "s":return 1E3*b;case "milliseconds":case "millisecond":case "msecs":case "msec":case "ms":return b}}}function x(a,b,c,d){return Math.round(a/c)+" "+d+(b>=1.5*c?"s":"")};/*
 bytes
 Copyright(c) 2012-2014 TJ Holowaychuk
 Copyright(c) 2015 Jed Watson
 MIT Licensed
*/
const y=/\B(?=(\d{3})+(?!\d))/g,A=/(?:\.0*|(\.[^0]+)0+)$/,B={b:1,kb:1024,mb:1048576,gb:1073741824,tb:Math.pow(1024,4),pb:Math.pow(1024,5)};function C(a,b){if(!Number.isFinite(a))return null;const c=Math.abs(a),d=b&&b.A||"",f=b&&b.C||"",e=b&&void 0!==b.m?b.m:2,g=!(!b||!b.u);(b=b&&b.B||"")&&B[b.toLowerCase()]||(b=c>=B.pb?"PB":c>=B.tb?"TB":c>=B.gb?"GB":c>=B.mb?"MB":c>=B.kb?"KB":"B");a=(a/B[b.toLowerCase()]).toFixed(e);g||(a=a.replace(A,"$1"));d&&(a=a.replace(y,d));return a+f+b};/*
 diff package https://github.com/kpdecker/jsdiff
 BSD License
 Copyright (c) 2009-2015, Kevin Decker <kpdecker@gmail.com>
*/
const D={black:30,red:31,green:32,yellow:33,blue:34,magenta:35,cyan:36,white:37,grey:90};function E(a,b){return(b=D[b])?`\x1b[${b}m${a}\x1b[0m`:a};var F={f:C,["fy"](a){return E(C(a)||"","yellow")},["fr"](a){return E(C(a)||"","red")},["fb"](a){return E(C(a)||"","blue")},["fg"](a){return E(C(a)||"","green")},["fc"](a){return E(C(a)||"","cyan")},["fm"](a){return E(C(a)||"","magenta")}};const G=Object.keys(process.env).filter(a=>/^debug_/i.test(a)).reduce((a,b)=>{const c=b.substring(6).toLowerCase().replace(/_([a-z])/g,(d,f)=>f.toUpperCase());b=process.env[b];/^(yes|on|true|enabled)$/i.test(b)?b=!0:/^(no|off|false|disabled)$/i.test(b)?b=!1:"null"===b?b=null:b=Number(b);a[c]=b;return a},{}),H={init:function(a){a.inspectOpts={...G}},log:function(...a){return process.stderr.write(t(...a)+"\n")},formatArgs:function(a){var b=this.namespace,c=this.color;const d=this.diff;this.useColors?
(c="\u001b[3"+(8>c?c:"8;5;"+c),b=`  ${c};1m${b} \u001B[0m`,a[0]=b+a[0].split("\n").join("\n"+b),a.push(c+"m+"+v(d)+"\u001b[0m")):a[0]=(G.hideDate?"":(new Date).toISOString()+" ")+b+" "+a[0]},save:function(a){a?process.env.DEBUG=a:delete process.env.DEBUG},load:function(){return process.env.DEBUG},useColors:function(){return"colors"in G?!!G.colors:r.isatty(process.stderr.fd)},colors:[6,2,3,4,5,1],inspectOpts:G,formatters:{o:function(a){return u(a,{...this.inspectOpts,colors:this.useColors}).replace(/\s*\n\s*/g,
" ")},O:function(a){return u(a,{...this.inspectOpts,colors:this.useColors})},...F}};function I(a){function b(...g){if(b.enabled){var h=Number(new Date);b.diff=h-(e||h);b.prev=e;e=b.curr=h;g[0]=J(g[0]);"string"!=typeof g[0]&&g.unshift("%O");var l=0;g[0]=g[0].replace(/%([a-zA-Z%]+)/g,(n,k)=>{if("%%"==n)return n;l++;if(k=c[k])n=k.call(b,g[l]),g.splice(l,1),l--;return n});d.call(b,g);(b.log||f).apply(b,g)}}const c=a.formatters,d=a.formatArgs,f=a.log;let e;return b}function K(a){const b=I(a);"function"==typeof a.init&&a.init(b);a.a.push(b);return b}
function L(a,b){let c=0;for(let d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d),c|=0;return a.colors[Math.abs(c)%a.colors.length]}function aa(a){var b=H.load();a.save(b);a.g=[];a.i=[];let c;const d=("string"==typeof b?b:"").split(/[\s,]+/),f=d.length;for(c=0;c<f;c++)d[c]&&(b=d[c].replace(/\*/g,".*?"),"-"==b[0]?a.i.push(new RegExp("^"+b.substr(1)+"$")):a.g.push(new RegExp("^"+b+"$")));for(c=0;c<a.a.length;c++)b=a.a[c],b.enabled=a.enabled(b.namespace)}
class ba{constructor(a){this.colors=a.colors;this.formatArgs=a.formatArgs;this.inspectOpts=a.inspectOpts;this.log=a.log;this.save=a.save;this.init=a.init;this.formatters=a.formatters||{};this.a=[];this.g=[];this.i=[]}destroy(a){a=this.a.indexOf(a);return-1!==a?(this.a.splice(a,1),!0):!1}enabled(a){if("*"==a[a.length-1])return!0;let b,c;b=0;for(c=this.i.length;b<c;b++)if(this.i[b].test(a))return!1;b=0;for(c=this.g.length;b<c;b++)if(this.g[b].test(a))return!0;return!1}}
function ca(){const a=new ba(H);return function(b){const c=K(a);c.namespace=b;c.useColors=H.useColors();c.enabled=a.enabled(b);c.color=L(a,b);c.destroy=function(){a.destroy(this)};c.extend=function(d,f){d=this.namespace+(void 0===f?":":f)+d;d.log=this.log;return d};aa(a);return c}}function J(a){return a instanceof Error?a.stack||a.message:a};function M(a){if(!a)throw Error("To use debug, pass the namespace.");return ca()(a)};/*
 MIT
 (c) dead-horse
 https://npmjs.org/koa-compose
*/
function da(a){if(!Array.isArray(a))throw new TypeError("Middleware stack must be an array!");for(const b of a)if("function"!=typeof b)throw new TypeError("Middleware must be composed of functions!");return(b,c)=>{function d(e){if(e<=f)return Promise.reject(Error("next() called multiple times"));f=e;let g=a[e];e==a.length&&(g=c);if(!g)return Promise.resolve();try{return Promise.resolve(g(b,d.bind(null,e+1)))}catch(h){return Promise.reject(h)}}let f=-1;return d(0)}};var N={[100]:"Continue",[101]:"Switching Protocols",[102]:"Processing",[103]:"Early Hints",[200]:"OK",[201]:"Created",[202]:"Accepted",[203]:"Non-Authoritative Information",[204]:"No Content",[205]:"Reset Content",[206]:"Partial Content",[207]:"Multi-Status",[208]:"Already Reported",[226]:"IM Used",[300]:"Multiple Choices",[301]:"Moved Permanently",[302]:"Found",[303]:"See Other",[304]:"Not Modified",[305]:"Use Proxy",[306]:"(Unused)",[307]:"Temporary Redirect",[308]:"Permanent Redirect",[400]:"Bad Request",
[401]:"Unauthorized",[402]:"Payment Required",[403]:"Forbidden",[404]:"Not Found",[405]:"Method Not Allowed",[406]:"Not Acceptable",[407]:"Proxy Authentication Required",[408]:"Request Timeout",[409]:"Conflict",[410]:"Gone",[411]:"Length Required",[412]:"Precondition Failed",[413]:"Payload Too Large",[414]:"URI Too Long",[415]:"Unsupported Media Type",[416]:"Range Not Satisfiable",[417]:"Expectation Failed",[418]:"I'm a teapot",[421]:"Misdirected Request",[422]:"Unprocessable Entity",[423]:"Locked",
[424]:"Failed Dependency",[425]:"Unordered Collection",[426]:"Upgrade Required",[428]:"Precondition Required",[429]:"Too Many Requests",[431]:"Request Header Fields Too Large",[451]:"Unavailable For Legal Reasons",[500]:"Internal Server Error",[501]:"Not Implemented",[502]:"Bad Gateway",[503]:"Service Unavailable",[504]:"Gateway Timeout",[505]:"HTTP Version Not Supported",[506]:"Variant Also Negotiates",[507]:"Insufficient Storage",[508]:"Loop Detected",[509]:"Bandwidth Limit Exceeded",[510]:"Not Extended",
[511]:"Network Authentication Required"};/*
 statuses
 Copyright(c) 2014 Jonathan Ong
 Copyright(c) 2016 Douglas Christopher Wilson
 MIT Licensed
*/
const fa=ea();function ea(){var a=O;const b=[];Object.keys(N).forEach(c=>{const d=N[c];c=Number(c);a[c]=d;a[d]=c;a[d.toLowerCase()]=c;b.push(c)});return b}
function O(a){if("number"==typeof a){if(!O[a])throw Error("invalid status code: "+a);return a}if("string"!=typeof a)throw new TypeError("code must be a number or string");var b=parseInt(a,10);if(!isNaN(b)){if(!O[b])throw Error("invalid status code: "+b);return b}b=O[a.toLowerCase()];if(!b)throw Error('invalid status message: "'+a+'"');return b};/*
 http-errors
 Copyright(c) 2014 Jonathan Ong
 Copyright(c) 2016 Douglas Christopher Wilson
 MIT Licensed
 toidentifier
 Copyright(c) 2016 Douglas Christopher Wilson
 MIT Licensed
*/
function P(...a){let b,c,d=500,f={};for(let e=0;e<a.length;e++){let g=a[e];if(g instanceof Error)b=g,d=b.status||b.statusCode||d;else switch(typeof g){case "string":c=g;break;case "number":d=g;0!==e&&process.emitWarning("non-first-argument status code; replace with createError("+g+", ...)","DeprecationWarning");break;case "object":f=g}}"number"==typeof d&&(400>d||600<=d)&&process.emitWarning("non-error status code; use only 4xx or 5xx status codes","DeprecationWarning");if("number"!=typeof d||!O[d]&&
(400>d||600<=d))d=500;a=P[d]||P[Number(String(d).charAt(0)+"00")];b||(b=a?new a(c):Error(c||O[d]),Error.captureStackTrace(b,P));a&&b instanceof a&&b.status===d||(b.expose=500>d,b.status=b.statusCode=d);for(let e in f)"status"!=e&&"statusCode"!=e&&(b[e]=f[e]);return b}class Q extends Error{constructor(a){super();this.message=a;this.statusCode=this.status=null;this.expose=!1;this.headers=null}set code(a){this.statusCode=this.status=a;this.message||(this.message=O[a])}}
fa.forEach(a=>{let b;const c=ha(O[a]),d=c.match(/Error$/)?c:c+"Error";switch(Number(String(a).charAt(0)+"00")){case 400:b=class extends Q{constructor(f){super(f);this.code=a;this.name=d;this.expose=!0}};break;case 500:b=class extends Q{constructor(f){super(f);this.code=a;this.name=d;this.expose=!1}}}b&&(P[a]=b,P[c]=b)},{});function ha(a){return a.split(" ").map(function(b){return b.charAt(0).toUpperCase()+b.slice(1)}).join("").replace(/[^ _0-9a-z]/gi,"")};const ia=http.METHODS;/*
 path-to-regexp
 The MIT License (MIT)
 Copyright (c) 2014 Blake Embrey (hello@blakeembrey.com)
*/
function ja(a){const b=[];let c=0;for(;c<a.length;){var d=a[c];if("*"===d||"+"===d||"?"===d)b.push({type:"MODIFIER",index:c,value:a[c++]});else if("\\"===d)b.push({type:"ESCAPED_CHAR",index:c++,value:a[c++]});else if("{"===d)b.push({type:"OPEN",index:c,value:a[c++]});else if("}"===d)b.push({type:"CLOSE",index:c,value:a[c++]});else if(":"===d){d="";for(var f=c+1;f<a.length;){var e=a.charCodeAt(f);if(48<=e&&57>=e||65<=e&&90>=e||97<=e&&122>=e||95===e)d+=a[f++];else break}if(!d)throw new TypeError(`Missing parameter name at ${c}`);
b.push({type:"NAME",index:c,value:d});c=f}else if("("===d){d=1;f="";e=c+1;if("?"===a[e])throw new TypeError(`Pattern cannot start with '?' at ${e}`);for(;e<a.length;)if("\\"===a[e])f+=a[e++]+a[e++];else{if(")"===a[e]){if(d--,0===d){e++;break}}else if("("===a[e]&&(d++,"?"!==a[e+1]))throw new TypeError(`Capturing groups are not allowed at ${e}`);f+=a[e++]}if(d)throw new TypeError(`Unbalanced pattern at ${c}`);if(!f)throw new TypeError(`Missing pattern at ${c}`);b.push({type:"PATTERN",index:c,value:f});
c=e}else b.push({type:"CHAR",index:c,value:a[c++]})}b.push({type:"END",index:c,value:""});return b}
function R(a,b={}){const c=ja(a);({w:a="./"}=b);b=`[^${S(b.s||"/#?")}]+?`;const d=[];let f=0,e=0,g="";const h=q=>{if(e<c.length&&c[e].type===q)return c[e++].value},l=q=>{const z=h(q);if(void 0!==z)return z;const {type:ka,index:la}=c[e];throw new TypeError(`Unexpected ${ka} at ${la}, expected ${q}`);},n=()=>{let q="",z;for(;z=h("CHAR")||h("ESCAPED_CHAR");)q+=z;return q};for(;e<c.length;){var k=h("CHAR"),p=h("NAME"),m=h("PATTERN");if(p||m)k=k||"",-1===a.indexOf(k)&&(g+=k,k=""),g&&(d.push(g),g=""),d.push({name:p||
f++,prefix:k,h:"",pattern:m||b,c:h("MODIFIER")||""});else if(p=k||h("ESCAPED_CHAR"))g+=p;else if(g&&(d.push(g),g=""),h("OPEN")){p=n();m=h("NAME")||"";k=h("PATTERN")||"";const q=n();l("CLOSE");d.push({name:m||(k?f++:""),pattern:m&&!k?b:k,prefix:p,h:q,c:h("MODIFIER")||""})}else l("END")}return d}function ma(a){var b={encode:encodeURIComponent};return na(R(a,b),b)}
function na(a,b={}){const c=T(b),{encode:d=g=>g,D:f=!0}=b,e=a.map(g=>{if("object"===typeof g)return new RegExp(`^(?:${g.pattern})$`,c)});return g=>{let h="";for(let p=0;p<a.length;p++){const m=a[p];if("string"===typeof m)h+=m;else{var l=g?g[m.name]:void 0,n="?"===m.c||"*"===m.c,k="*"===m.c||"+"===m.c;if(Array.isArray(l)){if(!k)throw new TypeError(`Expected '${m.name}' to not repeat, but got an array`);if(0===l.length){if(n)continue;throw new TypeError(`Expected '${m.name}' to not be empty`);}for(n=
0;n<l.length;n++){k=d(l[n],m);if(f&&!e[p].test(k))throw new TypeError(`Expected all '${m.name}' to match '${m.pattern}', but got '${k}'`);h+=m.prefix+k+m.h}}else if("string"===typeof l||"number"===typeof l){l=d(String(l),m);if(f&&!e[p].test(l))throw new TypeError(`Expected '${m.name}' to match '${m.pattern}', but got '${l}'`);h+=m.prefix+l+m.h}else if(!n)throw new TypeError(`Expected '${m.name}' to be ${k?"an array":"a string"}`);}}return h}}
function S(a){return a.replace(/([.+*?=^!:${}()[\]|/\\])/g,"\\$1")}function T(a={}){return a.sensitive?"":"i"}function oa(a,b,c){a=a.map(d=>U(d,b,c).source);return new RegExp(`(?:${a.join("|")})`,T(c))}
function pa(a,b,c={}){const {strict:d=!1,start:f=!0,end:e=!0,encode:g=k=>k}=c,h=`[${S(c.endsWith||"")}]|$`,l=`[${S(c.s||"/#?")}]`;let n=f?"^":"";for(const k of a)if("string"==typeof k)n+=S(g(k));else{const p=S(g(k.prefix)),m=S(g(k.h));k.pattern?(b&&b.push(k),n=p||m?"+"==k.c||"*"==k.c?n+`(?:${p}((?:${k.pattern})(?:${m}${p}(?:${k.pattern}))*)${m})${"*"==k.c?"?":""}`:n+`(?:${p}(${k.pattern})${m})${k.c}`:n+`(${k.pattern})${k.c}`):n+=`(?:${p}${m})${k.c}`}e?(d||(n+=`${l}?`),n+=c.endsWith?`(?=${h})`:"$"):
(a=a[a.length-1],a="string"===typeof a?-1<l.indexOf(a[a.length-1]):void 0===a,d||(n+=`(?:${l}(?=${h}))?`),a||(n+=`(?=${l}|${h})`));return new RegExp(n,T(c))}function U(a,b,c){if(a instanceof RegExp){if(b&&(c=a.source.match(/\((?!\?)/g)))for(var d=0;d<c.length;d++)b.push({name:d,prefix:"",h:"",c:"",pattern:""})}else Array.isArray(a)?d=oa(a,b,c):d=pa(R(a,c),b,c),a=d;return a};const qa=querystring.stringify;const ra=M("koa-router");function V(a,b){a.path&&(a.path=b+a.path,a.paramNames=[],b=a.path,a.g=U("string"==typeof b?b.replace(/\/$/,""):b,a.paramNames,a.a))}
class W{constructor(a,b,c,d={}){const {name:f=null}=d;this.a=d;this.name=f;this.methods=[];this.paramNames=[];this.stack=Array.isArray(c)?c:[c];b.forEach(e=>{e=this.methods.push(e.toUpperCase());"GET"==this.methods[e-1]&&this.methods.unshift("HEAD")});this.stack.forEach(e=>{e=typeof e;if("function"!=e)throw Error(b.toString()+" `"+(f||a)+"`: `middleware` must be a function, not `"+e+"`");});this.path=a;this.g=U("string"==typeof a?a.replace(/\/$/,""):a,this.paramNames,this.a);ra("defined route %s %s",
this.methods,this.a.prefix+this.path)}match(a){return this.g.test(a)}params(a,b,c={}){for(let e=b.length,g=0;g<e;g++)if(this.paramNames[g]){var d=b[g];a=this.paramNames[g].name;if(d)try{var f=decodeURIComponent(d)}catch(h){f=d}else f=d;c[a]=f}return c}j(a){return this.a.ignoreCaptures?[]:a.match(this.g).slice(1)}url(a,b){var c=a,d=this.path.replace(/\(\.\*\)/g,""),f=ma(d);"object"!=typeof a&&(c=[...arguments],"object"==typeof c[c.length-1]&&(b=c[c.length-1],c=c.slice(0,c.length-1)));d=R(d);let e=
{};if(Array.isArray(c))for(let g=d.length,h=0,l=0;h<g;h++)d[h].name&&(e[d[h].name]=c[l++]);else d.some(g=>g.name)?e=a:b=a;c=f(e);return b&&b.query?(f=b.query,f="string"==typeof f?f:qa(f),`${c}?${f}`):c}param(a,b){function c(e,g){return b.call(this,e.params[a],e,g)}c.param=a;const d=this.paramNames.map(({name:e})=>e),f=d.indexOf(a);-1<f&&this.stack.some((e,g)=>{if(!e.param||d.indexOf(e.param)>f)return this.stack.splice(g,0,c),!0});return this}};/*
 RESTful resource routing middleware for koa.

 @author Alex Mingoia <talk@alexmingoia.com>
 @link https://github.com/alexmingoia/koa-router
*/
const X=M("@goa/router");
class Y{constructor(a={}){const {methods:b="HEAD OPTIONS GET PUT PATCH POST DELETE".split(" ")}=a;this.opts=a;this.methods=b;this.params={};this.stack=[]}allowedMethods(a={}){const {throw:b=!1,notImplemented:c,methodNotAllowed:d}=a;return async(f,e)=>{await e();const g={};({status:e=404}=f);if(404==e)if(f.a.forEach(h=>{h.methods.forEach(l=>{g[l]=l})}),e=Object.keys(g),!this.methods.includes(f.method)){if(b){let h;"function"==typeof c?h=c():h=new P.NotImplemented;throw h;}f.status=501;f.set("Allow",
e.join(", "))}else if(e.length)if("OPTIONS"==f.method)f.status=200,f.body="",f.set("Allow",e.join(", "));else if(!g[f.method]){if(b){let h;"function"==typeof d?h=d():h=new P.MethodNotAllowed;throw h;}f.status=405;f.set("Allow",e.join(", "))}}}redirect(a,b,c=301){if("/"!=a[0]&&(a=this.url(a),a instanceof Error))throw a;if("/"!=b[0]){const d=this.url(b);if(d instanceof Error)throw d;b=d}return this.all(a,d=>{d.redirect(b);d.status=c})}register(a,b,c,d={}){const {ignoreCaptures:f,prefix:e=this.opts.prefix||
"",strict:g=this.opts.strict||!1,end:h=!0,name:l,sensitive:n=this.opts.sensitive||!1}=d;if(Array.isArray(a))return a.forEach(p=>{this.register(p,b,c,d)}),this;const k=new W(a,b,c,{end:h,name:l,sensitive:n,strict:g,prefix:e,ignoreCaptures:f});this.opts.prefix&&V(k,this.opts.prefix);Object.keys(this.params).forEach(p=>{k.param(p,this.params[p])});this.stack.push(k);return k}route(a){const b=this.stack;for(let c=b.length,d=0;d<c;d++)if(b[d].name&&b[d].name==a)return b[d];return null}url(a,...b){const c=
this.route(a);return c?c.url(...b):Error(`No route found for name: ${a}`)}match(a,b){const c=this.stack;let d;const f={path:[],l:[],route:!1};for(let e=c.length,g=0;g<e;g++)if(d=c[g],X("test %s %s",d.path,d.g),d.match(a)&&(f.path.push(d),0==d.methods.length||d.methods.includes(b)))f.l.push(d),d.methods.length&&(f.route=!0);return f}param(a,b){this.params[a]=b;this.stack.forEach(c=>{c.param(a,b)});return this}prefix(a){a=a.replace(/\/$/,"");this.opts.prefix=a;this.stack.forEach(b=>{V(b,a)});return this}use(a,
...b){if(Array.isArray(a)&&"string"==typeof a[0])return a.forEach(d=>{this.use(d,...b)}),this;const c="string"==typeof a;c||(b.unshift(a),a=null);b.forEach(d=>{const f=d.router;f?(f.stack.forEach(e=>{a&&V(e,a);this.opts.prefix&&V(e,this.opts.prefix);this.stack.push(e)}),this.params&&Object.keys(this.params).forEach(e=>{f.param(e,this.params[e])})):this.register(a||"(.*)",[],d,{end:!1,ignoreCaptures:!c})});return this}get routes(){return this.middleware}middleware(){const a=(b,c)=>{X("%s %s",b.method,
b.path);const d=this.opts.routerPath||b.routerPath||b.path;var f=this.match(d,b.method);b.a?b.a.push(f.path):b.a=f.path;b.router=this;if(!f.route)return c();f=f.l;const e=f[f.length-1];b._matchedRoute=e.path;e.name&&(b._matchedRouteName=e.name);f=f.reduce((g,h)=>{g.push((l,n)=>{l.j=h.j(d);l.params=h.params(d,l.j,l.params);l.g=h.name;return n()});return g.concat(h.stack)},[]);return da(f)(b,c)};a.router=this;return a}}Y.url=function(a,...b){return W.prototype.url.apply({path:a},b)};
const Z=ia.map(a=>a.toLowerCase());[...Z,"all"].forEach(a=>{function b(c,d,...f){"string"==typeof d||d instanceof RegExp||(f=[d,...f],d=c,c=null);this.register(d,"all"==a?Z:[a],f,{name:c});return this}Y.prototype[a]=b;"delete"==a&&(Y.prototype.del=b)});module.exports={_Router:Y};

//# sourceMappingURL=router.js.map